# Generated by Django 2.2.5 on 2020-03-16 17:40

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencyname', models.CharField(max_length=200)),
                ('registration_no', models.IntegerField()),
                ('agency_logo', pyuploadcare.dj.models.ImageField(blank=True)),
                ('agency_image', pyuploadcare.dj.models.ImageField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'agencies',
                'ordering': ['agencyname'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('profile_image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('agency', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agency.Agency')),
            ],
        ),
    ]
